name: CI - Build and Push Docker Images

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: read
      packages: write 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 0
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io 
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build affected apps
      run: npx turbo run build:image --filter="...[origin/${{ github.base_ref }}]"
      
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1
    # - name: Build and push Docker image
    #   run: |
    #     docker buildx build --platform linux/amd64,linux/arm64 -t ghcr.io/hansfigo/kagami-telegram-bot:latest -f apps/telegram-bot/Dockerfile . --push

